version: '0.5.4.dev.{build}'

environment:
  global:
    # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
    ANACONDA_TOKEN:
      secure: "8Wuonn7zuZIDXX26rNMQ+ivY6msM56v7d0TNUpQ7rUy291IxaW88aWDEPYDthTZ8"
    PYTHON_LOC: "C:\\Miniconda35-x64"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y conda-build anaconda-client

build_script:
  - cmd: conda build -c ccitools recipe
  - cmd: anaconda -v -t %ANACONDA_TOKEN% upload "%PYTHON_LOC%\conda-bld\win-64\dedop*.tar.bz2" -u dedop --force


artifacts:
  - path: 'DeDop*.exe'
    name: dedop-core-installer